Repository andela/strikers-ah-frontend, pull requests merged in 2019-06, with the labels that each got.

#16 #164489755 Users should follow each other
  package.json
  scripts/build.js
  src/components/article/Author.jsx
  src/components/common/FollowButton.jsx
  src/components/common/accountInfo.jsx
  src/helpers/axios.js
  src/redux/actionTypes/userTypes.js
  src/redux/actions/followingAction.js
  src/redux/reducers/ArticleInitialState.js
  src/redux/reducers/Following.js
  src/redux/reducers/index.js
  src/styles/css/followBtn.css
  src/styles/scss/followBtn.scss
  src/tests/components/common/FollowButton.test.js
  src/tests/components/common/__snapshots__/FollowButton.test.js.snap
Labels: feature, requested-review

#22 #164489749 User should be able to rate article
  package.json
  src/components/article/ReadArticle.jsx
  src/components/common/FollowButton.jsx
  src/components/common/Rate.jsx
  src/components/common/Ratings.jsx
  src/redux/actionTypes/articleType.js
  src/redux/actions/rateArticle.js
  src/redux/reducers/index.js
  src/redux/reducers/rateArticle.js
  src/styles/css/emoji.css
  src/styles/scss/emoji.scss
  src/tests/components/Rate.test.js
  src/tests/components/Rating.test.js
  src/tests/components/__snapshots__/Rate.test.js.snap
  src/tests/components/__snapshots__/Rating.test.js.snap
  src/tests/redux/actions/rateArticle.test.js
  src/tests/redux/reducers/rateArticle.test.js
Labels: feature, requested-review

#31 Feature Highlight and comment #164489763
  public/favicon.ico
  public/index.html
  public/manifest.json
  src/components/Login.jsx
  src/components/article/ReadArticle.jsx
  src/components/common/input.jsx
  src/components/form.jsx
  src/components/signup.jsx
  src/css/Home-styles/home-body-content-style.css.map
  src/css/Home-styles/home-style.css.map
  src/css/Home-styles/slide-show-style.css.map
  src/css/signup-style/signup-style.css
  src/css/signup-style/signup-style.css.map
  src/css/signup-style/signup-style.scss
  src/helpers/highlight.js
  src/styles/css/highlight.css
  src/styles/css/signup-style/signup-style.css
  src/styles/css/signup-style/signup-style.css.map
  src/styles/css/signup-style/signup-style.scss
  src/styles/img/commenting-icon.png
  src/styles/img/copy-icon.png
  src/styles/img/facebook-icon.png
  src/styles/img/logo.png
  src/styles/img/twitter-icon.png
  src/styles/scss/article.css
  src/styles/scss/article.css.map
  src/styles/scss/bookmarked.css
  src/styles/scss/bookmarked.css.map
  src/styles/scss/comment.css
  src/styles/scss/comment.css.map
  src/styles/scss/emoji.css
  src/styles/scss/emoji.css.map
  src/styles/scss/followBtn.css
  src/styles/scss/followBtn.css.map
  src/styles/scss/highlight.css
  src/styles/scss/highlight.css.map
  src/styles/scss/highlight.scss
  src/styles/scss/notificationButton.css
  src/styles/scss/notificationButton.css.map
  src/styles/scss/pagination.css
  src/styles/scss/pagination.css.map
  src/styles/scss/profile.css
  src/styles/scss/profile.css.map
  src/styles/scss/profileForm.css
  src/styles/scss/profileForm.css.map
  src/styles/scss/settings.css
  src/styles/scss/settings.css.map
  src/styles/scss/userArticle.css
  src/styles/scss/userArticle.css.map
Labels: feature

#34 adding the pop up to the forgot password form response
  src/components/ForgotPassword.jsx
  src/redux/actions/forgotPassword.js
  src/tests/redux/actions/forgotPassword.test.js
Labels: feature, requested-review

#39 Bug 166694856 user should follow each other
  package.json
  src/components/common/FollowButton.jsx
Labels: bug, requested-review, resolved

#40 Bug reset password bug fix
  src/components/ForgotPassword.jsx
  src/components/ResetPassword.jsx
  src/router.js
  src/tests/components/Forgotpassword.test.js
  src/tests/components/Resetpassword.test.js
Labels: bug, requested-review, resolved

#36 Feature View Article by under categories 166734412
  src/components/Category.jsx
  src/components/homeNavBar.jsx
  src/redux/actionTypes/articleType.js
  src/redux/actions/articleByCategory.js
  src/redux/reducers/articleByCategory.js
  src/redux/reducers/index.js
  src/router.js
  src/styles/css/category.css
  src/styles/scss/category.scss
  src/tests/components/Category.test.js
  src/tests/components/__snapshots__/Category.test.js.snap
  src/tests/redux/actions/articleByCategory.test.js
  src/tests/redux/reducers/articleByCategory.test.js
Labels: feature, requested-review

#47 adding the platform footer
  src/components/Category.jsx
  src/components/Footer.jsx
  src/components/Index.jsx
  src/components/Setting.jsx
  src/components/article/CreateArticle.jsx
  src/components/article/ReadArticle.jsx
  src/router.js
  src/styles/css/footer.css
  src/styles/scss/footer.scss
Labels: feature, requested-review
