Repository andela/strikers-ah-frontend, pull requests merged in 2019-05, with the labels that each got.

#7 #164489740 configuring react-router-dom version 5.
  package.json
  src/App.js
  src/components/Login.js
  src/router.js
Labels: chore, requested-review

#8 164489746 Users should be able to Login via Google, Facebook, Github or Twitter
  .eslintrc
  .gitignore
  package.json
  src/App.js
  src/components/Index.jsx
  src/components/Login.js
  src/components/Login.jsx
  src/components/SocialButtons.jsx
  src/redux/actions/userAction.js
  src/redux/reducers/index.js
  src/redux/reducers/userReducer.js
  src/redux/store.js
  src/router.js
  src/styles/css/login.css
  src/styles/img/logo.png
  src/styles/scss/login.scss
  src/tests/components/Login.test.js
  src/tests/components/__snapshots__/Login.test.js.snap
  src/tests/redux/actions/userAction.test.js
Labels: feature, requested-review

#11 Ft 164489744 user should be able to reset password
  package.json
  src/components/ForgotPassword.jsx
  src/components/Index.jsx
  src/components/Login.js
  src/components/Login.jsx
  src/components/ResetPassword.jsx
  src/components/SocialButtons.jsx
  src/components/common/CreateAccount.jsx
  src/components/common/InputForm.jsx
  src/components/common/SubmitButton.jsx
  src/redux/actionTypes/userTypes.js
  src/redux/actions/forgotPassword.js
  src/redux/actions/socialLogin.js
  src/redux/actions/userAction.js
  src/redux/reducers/index.js
  src/redux/reducers/resetpassword.js
  src/redux/reducers/socialLogin.js
  src/router.js
  src/styles/css/login.css
  src/styles/scss/login.scss
  src/tests/__snapshots__/routes.test.js.snap
  src/tests/components/Forgotpassword.test.js
  src/tests/components/Login.test.js
  src/tests/components/__snapshots__/Forgotpassword.test.js.snap
  src/tests/components/__snapshots__/Login.test.js.snap
  src/tests/components/common/CreateAccout.test.js
  src/tests/components/common/InputForm.test.js
  src/tests/components/common/__snapshots__/CreateAccout.test.js.snap
  src/tests/components/common/__snapshots__/InputForm.test.js.snap
  src/tests/redux/actions/resetPassword.js
  src/tests/routes.test.js
Labels: feature, requested-review

#10 Feature Implemented login # 164489745
  src/actions/login.actions.js
  src/actions/loginForm.js
  src/components/Login.jsx
  src/components/common/input.jsx
  src/redux/actionTypes/login.js
  src/redux/actionTypes/userTypes.js
  src/redux/reducers/index.js
  src/redux/reducers/login.reducers.js
  src/redux/reducers/loginForm.js
  src/router.js
  src/services/login.service.js
  src/styles/css/login.css
  src/styles/css/signup-style/notificationStyle.css
  src/styles/css/signup-style/notificationStyle.css.map
  src/styles/css/signup-style/notificationStyle.scss
  src/styles/css/signup-style/signup-style.css
  src/styles/css/signup-style/signup-style.css.map
  src/styles/css/signup-style/signup-style.scss
  src/styles/img/backgound-one.jpg
  src/styles/img/background-three.jpg
  src/styles/img/background-two.jpg
  src/styles/img/logo.png
  src/styles/scss/login.scss
  src/tests/components/Login.test.js
  src/tests/redux/actions/LoginAction.test.js
  src/tests/redux/services/LoginService.test.js
Labels: feature

#15 Ft select articles 164489748
  config/env.js
  config/jest/cssTransform.js
  config/jest/fileTransform.js
  config/modules.js
  config/paths.js
  config/pnpTs.js
  config/webpack.config.js
  config/webpackDevServer.config.js
  package.json
  scripts/build.js
  scripts/start.js
  scripts/test.js
  src/PrivateRoute.jsx
  src/components/Login.jsx
  src/components/article/Alert.jsx
  src/components/article/AllArticlesComponents.jsx
  src/components/article/ArticleForm.jsx
  src/components/article/Author.jsx
  src/components/article/CreateArticle.jsx
  src/components/article/DeleteButtons.jsx
  src/components/article/EditArticle.jsx
  src/components/article/EditorBar.jsx
  src/components/article/Header.jsx
  src/components/article/ReadArticle.jsx
  src/components/article/SocialMedia.jsx
  src/redux/actionTypes/articleType.js
  src/redux/actions/alert.js
  src/redux/actions/articleAction.js
  src/redux/reducers/alertReducer.js
  src/redux/reducers/articleReducer.js
  src/redux/reducers/index.js
  src/router.js
  src/styles/css/article.css
  src/styles/img/bookmark.svg
  src/styles/img/facebook.svg
  src/styles/img/headBook.jpeg
  src/styles/img/heart.svg
  src/styles/img/linked-in.svg
  src/styles/img/twitter.svg
  src/styles/scss/article.scss
  src/tests/article/ArticleReducers.test.js
  src/tests/article/articleActionsTest.test.js
  src/tests/article/components/Article.test.js
  src/tests/article/components/__snapshots__/Article.test.js.snap
Labels: feature
